[package]
org = "samith"
name = "resultcalculator"
version = "0.1.0"
distribution = "2201.9.0-20240502-141200-0a49fa42"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mi"
version = "0.1.0"
repository="local"

[path]
iconPath = "./icons"